################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../RTD/src/CDD_Mcl.c \
../RTD/src/CDD_Mcl_Ipw.c \
../RTD/src/Cache_Ip.c \
../RTD/src/Cache_Ip_HwAcc_ArmCoreMx.c \
../RTD/src/Clock_Ip.c \
../RTD/src/Clock_Ip_Data.c \
../RTD/src/Clock_Ip_Divider.c \
../RTD/src/Clock_Ip_DividerTrigger.c \
../RTD/src/Clock_Ip_ExtOsc.c \
../RTD/src/Clock_Ip_FracDiv.c \
../RTD/src/Clock_Ip_Frequency.c \
../RTD/src/Clock_Ip_Gate.c \
../RTD/src/Clock_Ip_IntOsc.c \
../RTD/src/Clock_Ip_Irq.c \
../RTD/src/Clock_Ip_Monitor.c \
../RTD/src/Clock_Ip_Pll.c \
../RTD/src/Clock_Ip_ProgFreqSwitch.c \
../RTD/src/Clock_Ip_Selector.c \
../RTD/src/Clock_Ip_Specific.c \
../RTD/src/Dem.c \
../RTD/src/Dem_stub.c \
../RTD/src/Det.c \
../RTD/src/Det_stub.c \
../RTD/src/Dio.c \
../RTD/src/Dio_Ipw.c \
../RTD/src/Dma_Ip.c \
../RTD/src/Dma_Ip_Driver_State.c \
../RTD/src/Dma_Ip_Hw_Access.c \
../RTD/src/Dma_Ip_Irq.c \
../RTD/src/Dma_Ip_Multicore.c \
../RTD/src/Emios_Mcl_Ip.c \
../RTD/src/Emios_Mcl_Ip_Irq.c \
../RTD/src/Emios_Pwm_Ip.c \
../RTD/src/Emios_Pwm_Ip_Irq.c \
../RTD/src/Etpu_Pwm_Ip.c \
../RTD/src/Etpu_Pwm_Ip_Irq.c \
../RTD/src/FlexPwm_Ip.c \
../RTD/src/FlexPwm_Ip_Irq.c \
../RTD/src/Flexio_Mcl_Ip.c \
../RTD/src/Flexio_Mcl_Ip_HwAccess.c \
../RTD/src/Flexio_Mcl_Ip_Irq.c \
../RTD/src/Flexio_Pwm_Ip.c \
../RTD/src/Flexio_Pwm_Ip_Irq.c \
../RTD/src/Igf_Port_Ip.c \
../RTD/src/Lcu_Ip.c \
../RTD/src/Lcu_Ip_Hw_Access.c \
../RTD/src/Lcu_Ip_Irq.c \
../RTD/src/Lcu_Ip_Multicore.c \
../RTD/src/Mcu.c \
../RTD/src/Mcu_Dem_Wrapper.c \
../RTD/src/Mcu_Ipw.c \
../RTD/src/OsIf_Interrupts.c \
../RTD/src/OsIf_Timer.c \
../RTD/src/OsIf_Timer_System.c \
../RTD/src/OsIf_Timer_System_Internal_Systick.c \
../RTD/src/Osif_Software_Semaphore.c \
../RTD/src/Port.c \
../RTD/src/Port_Ipw.c \
../RTD/src/Power_Ip.c \
../RTD/src/Power_Ip_AEC.c \
../RTD/src/Power_Ip_CortexM7.c \
../RTD/src/Power_Ip_DCM_GPR.c \
../RTD/src/Power_Ip_FLASH.c \
../RTD/src/Power_Ip_MC_ME.c \
../RTD/src/Power_Ip_MC_RGM.c \
../RTD/src/Power_Ip_MC_RGM_Irq.c \
../RTD/src/Power_Ip_PMC.c \
../RTD/src/Power_Ip_PMC_Irq.c \
../RTD/src/Power_Ip_Private.c \
../RTD/src/Pwm.c \
../RTD/src/Pwm_Ipw.c \
../RTD/src/Pwm_Ipw_Irq.c \
../RTD/src/Ram_Ip.c \
../RTD/src/SchM_Dio.c \
../RTD/src/SchM_Mcl.c \
../RTD/src/SchM_Mcu.c \
../RTD/src/SchM_Port.c \
../RTD/src/SchM_Pwm.c \
../RTD/src/Siul2_Dio_Ip.c \
../RTD/src/Siul2_Port_Ip.c \
../RTD/src/Trgmux_Ip.c \
../RTD/src/Trgmux_Ip_HwAcc.c \
../RTD/src/Tspc_Port_Ip.c 

OBJS += \
./RTD/src/CDD_Mcl.o \
./RTD/src/CDD_Mcl_Ipw.o \
./RTD/src/Cache_Ip.o \
./RTD/src/Cache_Ip_HwAcc_ArmCoreMx.o \
./RTD/src/Clock_Ip.o \
./RTD/src/Clock_Ip_Data.o \
./RTD/src/Clock_Ip_Divider.o \
./RTD/src/Clock_Ip_DividerTrigger.o \
./RTD/src/Clock_Ip_ExtOsc.o \
./RTD/src/Clock_Ip_FracDiv.o \
./RTD/src/Clock_Ip_Frequency.o \
./RTD/src/Clock_Ip_Gate.o \
./RTD/src/Clock_Ip_IntOsc.o \
./RTD/src/Clock_Ip_Irq.o \
./RTD/src/Clock_Ip_Monitor.o \
./RTD/src/Clock_Ip_Pll.o \
./RTD/src/Clock_Ip_ProgFreqSwitch.o \
./RTD/src/Clock_Ip_Selector.o \
./RTD/src/Clock_Ip_Specific.o \
./RTD/src/Dem.o \
./RTD/src/Dem_stub.o \
./RTD/src/Det.o \
./RTD/src/Det_stub.o \
./RTD/src/Dio.o \
./RTD/src/Dio_Ipw.o \
./RTD/src/Dma_Ip.o \
./RTD/src/Dma_Ip_Driver_State.o \
./RTD/src/Dma_Ip_Hw_Access.o \
./RTD/src/Dma_Ip_Irq.o \
./RTD/src/Dma_Ip_Multicore.o \
./RTD/src/Emios_Mcl_Ip.o \
./RTD/src/Emios_Mcl_Ip_Irq.o \
./RTD/src/Emios_Pwm_Ip.o \
./RTD/src/Emios_Pwm_Ip_Irq.o \
./RTD/src/Etpu_Pwm_Ip.o \
./RTD/src/Etpu_Pwm_Ip_Irq.o \
./RTD/src/FlexPwm_Ip.o \
./RTD/src/FlexPwm_Ip_Irq.o \
./RTD/src/Flexio_Mcl_Ip.o \
./RTD/src/Flexio_Mcl_Ip_HwAccess.o \
./RTD/src/Flexio_Mcl_Ip_Irq.o \
./RTD/src/Flexio_Pwm_Ip.o \
./RTD/src/Flexio_Pwm_Ip_Irq.o \
./RTD/src/Igf_Port_Ip.o \
./RTD/src/Lcu_Ip.o \
./RTD/src/Lcu_Ip_Hw_Access.o \
./RTD/src/Lcu_Ip_Irq.o \
./RTD/src/Lcu_Ip_Multicore.o \
./RTD/src/Mcu.o \
./RTD/src/Mcu_Dem_Wrapper.o \
./RTD/src/Mcu_Ipw.o \
./RTD/src/OsIf_Interrupts.o \
./RTD/src/OsIf_Timer.o \
./RTD/src/OsIf_Timer_System.o \
./RTD/src/OsIf_Timer_System_Internal_Systick.o \
./RTD/src/Osif_Software_Semaphore.o \
./RTD/src/Port.o \
./RTD/src/Port_Ipw.o \
./RTD/src/Power_Ip.o \
./RTD/src/Power_Ip_AEC.o \
./RTD/src/Power_Ip_CortexM7.o \
./RTD/src/Power_Ip_DCM_GPR.o \
./RTD/src/Power_Ip_FLASH.o \
./RTD/src/Power_Ip_MC_ME.o \
./RTD/src/Power_Ip_MC_RGM.o \
./RTD/src/Power_Ip_MC_RGM_Irq.o \
./RTD/src/Power_Ip_PMC.o \
./RTD/src/Power_Ip_PMC_Irq.o \
./RTD/src/Power_Ip_Private.o \
./RTD/src/Pwm.o \
./RTD/src/Pwm_Ipw.o \
./RTD/src/Pwm_Ipw_Irq.o \
./RTD/src/Ram_Ip.o \
./RTD/src/SchM_Dio.o \
./RTD/src/SchM_Mcl.o \
./RTD/src/SchM_Mcu.o \
./RTD/src/SchM_Port.o \
./RTD/src/SchM_Pwm.o \
./RTD/src/Siul2_Dio_Ip.o \
./RTD/src/Siul2_Port_Ip.o \
./RTD/src/Trgmux_Ip.o \
./RTD/src/Trgmux_Ip_HwAcc.o \
./RTD/src/Tspc_Port_Ip.o 

C_DEPS += \
./RTD/src/CDD_Mcl.d \
./RTD/src/CDD_Mcl_Ipw.d \
./RTD/src/Cache_Ip.d \
./RTD/src/Cache_Ip_HwAcc_ArmCoreMx.d \
./RTD/src/Clock_Ip.d \
./RTD/src/Clock_Ip_Data.d \
./RTD/src/Clock_Ip_Divider.d \
./RTD/src/Clock_Ip_DividerTrigger.d \
./RTD/src/Clock_Ip_ExtOsc.d \
./RTD/src/Clock_Ip_FracDiv.d \
./RTD/src/Clock_Ip_Frequency.d \
./RTD/src/Clock_Ip_Gate.d \
./RTD/src/Clock_Ip_IntOsc.d \
./RTD/src/Clock_Ip_Irq.d \
./RTD/src/Clock_Ip_Monitor.d \
./RTD/src/Clock_Ip_Pll.d \
./RTD/src/Clock_Ip_ProgFreqSwitch.d \
./RTD/src/Clock_Ip_Selector.d \
./RTD/src/Clock_Ip_Specific.d \
./RTD/src/Dem.d \
./RTD/src/Dem_stub.d \
./RTD/src/Det.d \
./RTD/src/Det_stub.d \
./RTD/src/Dio.d \
./RTD/src/Dio_Ipw.d \
./RTD/src/Dma_Ip.d \
./RTD/src/Dma_Ip_Driver_State.d \
./RTD/src/Dma_Ip_Hw_Access.d \
./RTD/src/Dma_Ip_Irq.d \
./RTD/src/Dma_Ip_Multicore.d \
./RTD/src/Emios_Mcl_Ip.d \
./RTD/src/Emios_Mcl_Ip_Irq.d \
./RTD/src/Emios_Pwm_Ip.d \
./RTD/src/Emios_Pwm_Ip_Irq.d \
./RTD/src/Etpu_Pwm_Ip.d \
./RTD/src/Etpu_Pwm_Ip_Irq.d \
./RTD/src/FlexPwm_Ip.d \
./RTD/src/FlexPwm_Ip_Irq.d \
./RTD/src/Flexio_Mcl_Ip.d \
./RTD/src/Flexio_Mcl_Ip_HwAccess.d \
./RTD/src/Flexio_Mcl_Ip_Irq.d \
./RTD/src/Flexio_Pwm_Ip.d \
./RTD/src/Flexio_Pwm_Ip_Irq.d \
./RTD/src/Igf_Port_Ip.d \
./RTD/src/Lcu_Ip.d \
./RTD/src/Lcu_Ip_Hw_Access.d \
./RTD/src/Lcu_Ip_Irq.d \
./RTD/src/Lcu_Ip_Multicore.d \
./RTD/src/Mcu.d \
./RTD/src/Mcu_Dem_Wrapper.d \
./RTD/src/Mcu_Ipw.d \
./RTD/src/OsIf_Interrupts.d \
./RTD/src/OsIf_Timer.d \
./RTD/src/OsIf_Timer_System.d \
./RTD/src/OsIf_Timer_System_Internal_Systick.d \
./RTD/src/Osif_Software_Semaphore.d \
./RTD/src/Port.d \
./RTD/src/Port_Ipw.d \
./RTD/src/Power_Ip.d \
./RTD/src/Power_Ip_AEC.d \
./RTD/src/Power_Ip_CortexM7.d \
./RTD/src/Power_Ip_DCM_GPR.d \
./RTD/src/Power_Ip_FLASH.d \
./RTD/src/Power_Ip_MC_ME.d \
./RTD/src/Power_Ip_MC_RGM.d \
./RTD/src/Power_Ip_MC_RGM_Irq.d \
./RTD/src/Power_Ip_PMC.d \
./RTD/src/Power_Ip_PMC_Irq.d \
./RTD/src/Power_Ip_Private.d \
./RTD/src/Pwm.d \
./RTD/src/Pwm_Ipw.d \
./RTD/src/Pwm_Ipw_Irq.d \
./RTD/src/Ram_Ip.d \
./RTD/src/SchM_Dio.d \
./RTD/src/SchM_Mcl.d \
./RTD/src/SchM_Mcu.d \
./RTD/src/SchM_Port.d \
./RTD/src/SchM_Pwm.d \
./RTD/src/Siul2_Dio_Ip.d \
./RTD/src/Siul2_Port_Ip.d \
./RTD/src/Trgmux_Ip.d \
./RTD/src/Trgmux_Ip_HwAcc.d \
./RTD/src/Tspc_Port_Ip.d 


# Each subdirectory must supply rules for building sources it contributes
RTD/src/%.o: ../RTD/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Standard S32DS C Compiler'
	arm-none-eabi-gcc "@RTD/src/CDD_Mcl.args" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


